name: Pull Request

on:
  pull_request:
    branches: ['main']

jobs:
  pull_request:
    uses: makerxstudio/shared-config/.github/workflows/node-ci.yml@main
    with:
      node-version: lts/*
      working-directory: ./
      run-commit-lint: true
      run-build: true
      pre-run-script: npm ci --prefix ./src/lambda
