name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: release

permissions:
  contents: write
  issues: read

jobs:
  ci:
    name: Continuous Integration
    uses: makerxstudio/shared-config/.github/workflows/node-ci.yml@main
    with:
      node-version: lts/*
      working-directory: ./
      run-commit-lint: true
      pre-run-script: npm ci --prefix ./src/lambda

  build:
    name: Build
    uses: makerxstudio/shared-config/.github/workflows/node-build-zip.yml@main
    needs:
      - ci
    with:
      node-version: lts/*
      build-path: build
      artifact-name: package
      pre-run-script: npm ci --prefix ./src/lambda

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # semantic-release needs node 20
      - name: Use Node.js lts/*
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Download built package
        uses: actions/download-artifact@v4
        with:
          name: package
          path: artifacts

      - name: Unzip package
        shell: bash
        run: |
          mkdir -p build
          unzip -q "artifacts/package.zip" -d build

      - name: Install dependencies to get semantic release components and plugins
        run: npm ci --ignore-scripts

      - name: 'Semantic release'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
